spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      # DatabaseInitializationMode
      mode: never
logging:
  level:
    org.springframework.web: "info"
    com.example.demo.mapper.CountryMapper: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  banner: false